version: '3'
services:
  db:
    image: postgres
    restart: always
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on: 
      - db
volumes:
  database-data: