version: '3'
services:
  db:
    image: postgres
    restart: always
    env_file:
    - envs/dev.env
    ports:
    - 5432:5432
    volumes:
    - database-data:/var/lib/postgresql/data/
    networks:
    - score-network

  migration:
    build:
      context: .
      target: score-migration
    restart: on-failure
    env_file:
    - envs/dev.env
    networks:
    - score-network
    depends_on: 
    - db

  server:
    build:
      context: .
      target: score-server
    env_file:
    - envs/dev.env
    ports:
    - 5000:5000
    networks:
    - score-network
    depends_on:
    - migration

volumes:
  database-data:

networks:
  score-network:
    driver: bridge