### 200

POST /scores
Host: localhost:5000
Authorization: abcd1234
Accept: application/json

{
    "cpf": "123.456.789-12"
}

### 422 (length)

GET /scores/123.456.789-12
Host: localhost:5000
Authorization: abcd1234
Accept: application/json

### 404

GET /
Host: localhost:5000
Content-Type: application/json

### 404

GET /abc
Host: localhost:5000
Authorization: abcd1234
Content-Type: application/json
### 404

GET /scores
Host: localhost:5000
Authorization: abcd1234
Accept: application/json

### 422 (length)

GET /scores/065.591.569-902
Host: localhost:5000
Authorization: abcd1234
Accept: application/json

### 422 (length)

POST /scores
Host: localhost:5000
Authorization: abcd1234
Accept: application/json

{
    "cpf": "1"
}

### 422 (letter)

POST /scores
Host: localhost:5000
Authorization: abcd1234
Accept: application/json

{
    "cpf": "0000000000a"
}

### 400

POST /scores
Host: localhost:5000
Authorization: abcd1234
Accept: application/json

{
    "cpf""999.999.999-99"
}

### 401

GET /scores/1
Host: localhost:5000
Authorization: abcd1
Accept: application/json

### 401

GET /scores/1
Host: localhost:5000
Accept: application/json